move 001.dds "1- Air Strike/DDS/1- Factory New/c_atom_launcher.dds"
move 002.dds "1- Air Strike/DDS/2- Minimal Wear/c_atom_launcher.dds"
move 003.dds "1- Air Strike/DDS/3- Field-Tested/c_atom_launcher.dds"
move 004.dds "1- Air Strike/DDS/4- Well-Worn/c_atom_launcher.dds"
move 005.dds "1- Air Strike/DDS/5- Battle Scarred/c_atom_launcher.dds"
move 006.dds "2- Air Strike (BLU)/DDS/1- Factory New/c_atom_launcher.dds"
move 007.dds "2- Air Strike (BLU)/DDS/2- Minimal Wear/c_atom_launcher.dds"
move 008.dds "2- Air Strike (BLU)/DDS/3- Field-Tested/c_atom_launcher.dds"
move 009.dds "2- Air Strike (BLU)/DDS/4- Well-Worn/c_atom_launcher.dds"
move 00A.dds "2- Air Strike (BLU)/DDS/5- Battle Scarred/c_atom_launcher.dds"

move 00B.dds "3- Amputator/DDS/1- Factory New/c_amputator.dds"
move 00C.dds "3- Amputator/DDS/2- Minimal Wear/c_amputator.dds"
move 00D.dds "3- Amputator/DDS/3- Field-Tested/c_amputator.dds"
move 00E.dds "3- Amputator/DDS/4- Well-Worn/c_amputator.dds"
move 00F.dds "3- Amputator/DDS/5- Battle Scarred/c_amputator.dds"
move 00G.dds "4- Amputator (BLU)/DDS/1- Factory New/c_amputator_blue.dds"
move 00H.dds "4- Amputator (BLU)/DDS/2- Minimal Wear/c_amputator_blue.dds"
move 00I.dds "4- Amputator (BLU)/DDS/3- Field-Tested/c_amputator_blue.dds"
move 00J.dds "4- Amputator (BLU)/DDS/4- Well-Worn/c_amputator_blue.dds"
move 00K.dds "4- Amputator (BLU)/DDS/5- Battle Scarred/c_amputator_blue.dds"

move 00L.dds "5- Back Scratcher/DDS/1- Factory New/c_back_scratcher.dds"
move 00M.dds "5- Back Scratcher/DDS/2- Minimal Wear/c_back_scratcher.dds"
move 00N.dds "5- Back Scratcher/DDS/3- Field-Tested/c_back_scratcher.dds"
move 00O.dds "5- Back Scratcher/DDS/4- Well-Worn/c_back_scratcher.dds"
move 00P.dds "5- Back Scratcher/DDS/5- Battle Scarred/c_back_scratcher.dds"
move 00Q.dds "6- Back Scratcher (BLU)/DDS/1- Factory New/c_back_scratcher.dds"
move 00R.dds "6- Back Scratcher (BLU)/DDS/2- Minimal Wear/c_back_scratcher.dds"
move 00S.dds "6- Back Scratcher (BLU)/DDS/3- Field-Tested/c_back_scratcher.dds"
move 00T.dds "6- Back Scratcher (BLU)/DDS/4- Well-Worn/c_back_scratcher.dds"
move 00U.dds "6- Back Scratcher (BLU)/DDS/5- Battle Scarred/c_back_scratcher.dds"

move 00V.dds "7- Bazaar Bargain/DDS/1- Factory New/c_bazaar_sniper.dds"
move 00W.dds "7- Bazaar Bargain/DDS/2- Minimal Wear/c_bazaar_sniper.dds"
move 00X.dds "7- Bazaar Bargain/DDS/3- Field-Tested/c_bazaar_sniper.dds"
move 00Y.dds "7- Bazaar Bargain/DDS/4- Well-Worn/c_bazaar_sniper.dds"
move 00Z.dds "7- Bazaar Bargain/DDS/5- Battle Scarred/c_bazaar_sniper.dds"
move 010.dds "8- Bazaar Bargain (BLU)/DDS/1- Factory New/c_bazaar_sniper.dds"
move 011.dds "8- Bazaar Bargain (BLU)/DDS/2- Minimal Wear/c_bazaar_sniper.dds"
move 012.dds "8- Bazaar Bargain (BLU)/DDS/3- Field-Tested/c_bazaar_sniper.dds"
move 013.dds "8- Bazaar Bargain (BLU)/DDS/4- Well-Worn/c_bazaar_sniper.dds"
move 014.dds "8- Bazaar Bargain (BLU)/DDS/5- Battle Scarred/c_bazaar_sniper.dds"

move 015.dds "9- Black Box/DDS/1- Factory New/c_blackbox.dds"
move 016.dds "9- Black Box/DDS/2- Minimal Wear/c_blackbox.dds"
move 017.dds "9- Black Box/DDS/3- Field-Tested/c_blackbox.dds"
move 018.dds "9- Black Box/DDS/4- Well-Worn/c_blackbox.dds"
move 019.dds "9- Black Box/DDS/5- Battle Scarred/c_blackbox.dds"
move 01A.dds "10- Black Box (BLU)/DDS/1- Factory New/c_blackbox.dds"
move 01B.dds "10- Black Box (BLU)/DDS/2- Minimal Wear/c_blackbox.dds"
move 01C.dds "10- Black Box (BLU)/DDS/3- Field-Tested/c_blackbox.dds"
move 01D.dds "10- Black Box (BLU)/DDS/4- Well-Worn/c_blackbox.dds"
move 01E.dds "10- Black Box (BLU)/DDS/5- Battle Scarred/c_blackbox.dds"

move 01F.dds "11- Brass Beast/DDS/1- Factory New/c_gatling_gun.dds"
move 01G.dds "11- Brass Beast/DDS/2- Minimal Wear/c_gatling_gun.dds"
move 01H.dds "11- Brass Beast/DDS/3- Field-Tested/c_gatling_gun.dds"
move 01I.dds "11- Brass Beast/DDS/4- Well-Worn/c_gatling_gun.dds"
move 01J.dds "11- Brass Beast/DDS/5- Battle Scarred/c_gatling_gun.dds"
move 01K.dds "12- Brass Beast (BLU)/DDS/1- Factory New/c_gatling_gun.dds"
move 01L.dds "12- Brass Beast (BLU)/DDS/2- Minimal Wear/c_gatling_gun.dds"
move 01M.dds "12- Brass Beast (BLU)/DDS/3- Field-Tested/c_gatling_gun.dds"
move 01N.dds "12- Brass Beast (BLU)/DDS/4- Well-Worn/c_gatling_gun.dds"
move 01O.dds "12- Brass Beast (BLU)/DDS/5- Battle Scarred/c_gatling_gun.dds"

move 01P.dds "13- Claidheamh Mor/DDS/1- Factory New/c_claidheamohmor.dds"
move 01Q.dds "13- Claidheamh Mor/DDS/2- Minimal Wear/c_claidheamohmor.dds"
move 01R.dds "13- Claidheamh Mor/DDS/3- Field-Tested/c_claidheamohmor.dds"
move 01S.dds "13- Claidheamh Mor/DDS/4- Well-Worn/c_claidheamohmor.dds"
move 01T.dds "13- Claidheamh Mor/DDS/5- Battle Scarred/c_claidheamohmor.dds"
move 01U.dds "14- Claidheamh Mor (BLU)/DDS/1- Factory New/c_claidheamohmor_blu.dds"
move 01V.dds "14- Claidheamh Mor (BLU)/DDS/2- Minimal Wear/c_claidheamohmor_blu.dds"
move 01W.dds "14- Claidheamh Mor (BLU)/DDS/3- Field-Tested/c_claidheamohmor_blu.dds"
move 01X.dds "14- Claidheamh Mor (BLU)/DDS/4- Well-Worn/c_claidheamohmor_blu.dds"
move 01Y.dds "14- Claidheamh Mor (BLU)/DDS/5- Battle Scarred/c_claidheamohmor_blu.dds"

move 01Z.dds "15- Crusader's Crossbow/DDS/1- Factory New/c_crusaders_crossbow.dds"
move 020.dds "15- Crusader's Crossbow/DDS/2- Minimal Wear/c_crusaders_crossbow.dds"
move 021.dds "15- Crusader's Crossbow/DDS/3- Field-Tested/c_crusaders_crossbow.dds"
move 022.dds "15- Crusader's Crossbow/DDS/4- Well-Worn/c_crusaders_crossbow.dds"
move 023.dds "15- Crusader's Crossbow/DDS/5- Battle Scarred/c_crusaders_crossbow.dds"
move 024.dds "16- Crusader's Crossbow (BLU)/DDS/1- Factory New/c_crusaders_crossbow_blue.dds"
move 025.dds "16- Crusader's Crossbow (BLU)/DDS/2- Minimal Wear/c_crusaders_crossbow_blue.dds"
move 026.dds "16- Crusader's Crossbow (BLU)/DDS/3- Field-Tested/c_crusaders_crossbow_blue.dds"
move 027.dds "16- Crusader's Crossbow (BLU)/DDS/4- Well-Worn/c_crusaders_crossbow_blue.dds"
move 028.dds "16- Crusader's Crossbow (BLU)/DDS/5- Battle Scarred/c_crusaders_crossbow_blue.dds"

move 029.dds "17- Degreaser/DDS/1- Factory New/c_degreaser_red.dds"
move 02A.dds "17- Degreaser/DDS/2- Minimal Wear/c_degreaser_red.dds"
move 02B.dds "17- Degreaser/DDS/3- Field-Tested/c_degreaser_red.dds"
move 02C.dds "17- Degreaser/DDS/4- Well-Worn/c_degreaser_red.dds"
move 02D.dds "17- Degreaser/DDS/5- Battle Scarred/c_degreaser_red.dds"
move 02E.dds "18- Degreaser (BLU)/DDS/1- Factory New/c_degreaser_blue.dds"
move 02F.dds "18- Degreaser (BLU)/DDS/2- Minimal Wear/c_degreaser_blue.dds"
move 02G.dds "18- Degreaser (BLU)/DDS/3- Field-Tested/c_degreaser_blue.dds"
move 02H.dds "18- Degreaser (BLU)/DDS/4- Well-Worn/c_degreaser_blue.dds"
move 02I.dds "18- Degreaser (BLU)/DDS/5- Battle Scarred/c_degreaser_blue.dds"

move 02J.dds "19- Detonator/DDS/1- Factory New/c_detonator.dds"
move 02K.dds "19- Detonator/DDS/2- Minimal Wear/c_detonator.dds"
move 02L.dds "19- Detonator/DDS/3- Field-Tested/c_detonator.dds"
move 02M.dds "19- Detonator/DDS/4- Well-Worn/c_detonator.dds"
move 02N.dds "19- Detonator/DDS/5- Battle Scarred/c_detonator.dds"
move 02O.dds "20- Detonator (BLU)/DDS/1- Factory New/c_detonator_blue"
move 02P.dds "20- Detonator (BLU)/DDS/2- Minimal Wear/c_detonator_blue"
move 02Q.dds "20- Detonator (BLU)/DDS/3- Field-Tested/c_detonator_blue"
move 02R.dds "20- Detonator (BLU)/DDS/4- Well-Worn/c_detonator_blue"
move 02S.dds "20- Detonator (BLU)/DDS/5- Battle Scarred/c_detonator_blue"

move 02T.dds "21- Disciplinary Action/DDS/1- Factory New/c_riding_crop.dds"
move 02U.dds "21- Disciplinary Action/DDS/2- Minimal Wear/c_riding_crop.dds"
move 02V.dds "21- Disciplinary Action/DDS/3- Field-Tested/c_riding_crop.dds"
move 02W.dds "21- Disciplinary Action/DDS/4- Well-Worn/c_riding_crop.dds"
move 02X.dds "21- Disciplinary Action/DDS/5- Battle Scarred/c_riding_crop.dds"
move 02Y.dds "22- Disciplinary Action (BLU)/DDS/1- Factory New/c_riding_crop.dds"
move 02Z.dds "22- Disciplinary Action (BLU)/DDS/2- Minimal Wear/c_riding_crop.dds"
move 030.dds "22- Disciplinary Action (BLU)/DDS/3- Field-Tested/c_riding_crop.dds"
move 031.dds "22- Disciplinary Action (BLU)/DDS/4- Well-Worn/c_riding_crop.dds"
move 032.dds "22- Disciplinary Action (BLU)/DDS/5- Battle Scarred/c_riding_crop.dds"

move 033.dds "23- Family Business/DDS/1- Factory New/c_russian_riot.dds"
move 034.dds "23- Family Business/DDS/2- Minimal Wear/c_russian_riot.dds"
move 035.dds "23- Family Business/DDS/3- Field-Tested/c_russian_riot.dds"
move 036.dds "23- Family Business/DDS/4- Well-Worn/c_russian_riot.dds"
move 037.dds "23- Family Business/DDS/5- Battle Scarred/c_russian_riot.dds"
move 038.dds "24- Family Business (BLU)/DDS/1- Factory New/c_russian_riot.dds"
move 039.dds "24- Family Business (BLU)/DDS/2- Minimal Wear/c_russian_riot.dds"
move 03A.dds "24- Family Business (BLU)/DDS/3- Field-Tested/c_russian_riot.dds"
move 03B.dds "24- Family Business (BLU)/DDS/4- Well-Worn/c_russian_riot.dds"
move 03C.dds "24- Family Business (BLU)/DDS/5- Battle Scarred/c_russian_riot.dds"

move 03D.dds "25- Flame Thrower/DDS/1- Factory New/c_flamethrower.dds"
move 03E.dds "25- Flame Thrower/DDS/2- Minimal Wear/c_flamethrower.dds"
move 03F.dds "25- Flame Thrower/DDS/3- Field-Tested/c_flamethrower.dds"
move 03G.dds "25- Flame Thrower/DDS/4- Well-Worn/c_flamethrower.dds"
move 03H.dds "25- Flame Thrower/DDS/5- Battle Scarred/c_flamethrower.dds"
move 03I.dds "26- Flame Thrower (BLU)/DDS/1- Factory New/c_flamethrower_blue.dds"
move 03J.dds "26- Flame Thrower (BLU)/DDS/2- Minimal Wear/c_flamethrower_blue.dds"
move 03K.dds "26- Flame Thrower (BLU)/DDS/3- Field-Tested/c_flamethrower_blue.dds"
move 03L.dds "26- Flame Thrower (BLU)/DDS/4- Well-Worn/c_flamethrower_blue.dds"
move 03M.dds "26- Flame Thrower (BLU)/DDS/5- Battle Scarred/c_flamethrower_blue.dds"

move 03N.dds "27- Grenade Launcher/DDS/1- Factory New/c_grenadelauncher.dds"
move 03O.dds "27- Grenade Launcher/DDS/2- Minimal Wear/c_grenadelauncher.dds"
move 03P.dds "27- Grenade Launcher/DDS/3- Field-Tested/c_grenadelauncher.dds"
move 03Q.dds "27- Grenade Launcher/DDS/4- Well-Worn/c_grenadelauncher.dds"
move 03R.dds "27- Grenade Launcher/DDS/5- Battle Scarred/c_grenadelauncher.dds"
move 03S.dds "28- Grenade Launcher (BLU)/DDS/1- Factory New/c_grenadelauncher.dds"
move 03T.dds "28- Grenade Launcher (BLU)/DDS/2- Minimal Wear/c_grenadelauncher.dds"
move 03U.dds "28- Grenade Launcher (BLU)/DDS/3- Field-Tested/c_grenadelauncher.dds"
move 03V.dds "28- Grenade Launcher (BLU)/DDS/4- Well-Worn/c_grenadelauncher.dds"
move 03W.dds "28- Grenade Launcher (BLU)/DDS/5- Battle Scarred/c_grenadelauncher.dds"

move 03X.dds "29- Holy Mackerel/DDS/1- Factory New/c_holymackerel.dds"
move 03Y.dds "29- Holy Mackerel/DDS/2- Minimal Wear/c_holymackerel.dds"
move 03Z.dds "29- Holy Mackerel/DDS/3- Field-Tested/c_holymackerel.dds"
move 040.dds "29- Holy Mackerel/DDS/4- Well-Worn/c_holymackerel.dds"
move 041.dds "29- Holy Mackerel/DDS/5- Battle Scarred/c_holymackerel.dds"
move 042.dds "30- Holy Mackerel (BLU)/DDS/1- Factory New/c_holymackerel.dds"
move 043.dds "30- Holy Mackerel (BLU)/DDS/2- Minimal Wear/c_holymackerel.dds"
move 044.dds "30- Holy Mackerel (BLU)/DDS/3- Field-Tested/c_holymackerel.dds"
move 045.dds "30- Holy Mackerel (BLU)/DDS/4- Well-Worn/c_holymackerel.dds"
move 046.dds "30- Holy Mackerel (BLU)/DDS/5- Battle Scarred/c_holymackerel.dds"

move 047.dds "31- Iron Bomber/DDS/1- Factory New/c_quadball.dds"
move 048.dds "31- Iron Bomber/DDS/2- Minimal Wear/c_quadball.dds"
move 049.dds "31- Iron Bomber/DDS/3- Field-Tested/c_quadball.dds"
move 04A.dds "31- Iron Bomber/DDS/4- Well-Worn/c_quadball.dds"
move 04B.dds "31- Iron Bomber/DDS/5- Battle Scarred/c_quadball.dds"
move 04C.dds "32- Iron Bomber (BLU)/DDS/1- Factory New/c_quadball.dds"
move 04D.dds "32- Iron Bomber (BLU)/DDS/2- Minimal Wear/c_quadball.dds"
move 04E.dds "32- Iron Bomber (BLU)/DDS/3- Field-Tested/c_quadball.dds"
move 04F.dds "32- Iron Bomber (BLU)/DDS/4- Well-Worn/c_quadball.dds"
move 04G.dds "32- Iron Bomber (BLU)/DDS/5- Battle Scarred/c_quadball.dds"

move 04H.dds "33- Jag/DDS/1- Factory New/c_jag.dds"
move 04I.dds "33- Jag/DDS/2- Minimal Wear/c_jag.dds"
move 04J.dds "33- Jag/DDS/3- Field-Tested/c_jag.dds"
move 04K.dds "33- Jag/DDS/4- Well-Worn/c_jag.dds"
move 04L.dds "33- Jag/DDS/5- Battle Scarred/c_jag.dds"
move 04M.dds "34- Jag (BLU)/DDS/1- Factory New/c_jag.dds"
move 04N.dds "34- Jag (BLU)/DDS/2- Minimal Wear/c_jag.dds"
move 04O.dds "34- Jag (BLU)/DDS/3- Field-Tested/c_jag.dds"
move 04P.dds "34- Jag (BLU)/DDS/4- Well-Worn/c_jag.dds"
move 04Q.dds "34- Jag (BLU)/DDS/5- Battle Scarred/c_jag.dds"

move 04R.dds "35- Knife/DDS/1- Factory New/c_knife.dds"
move 04S.dds "35- Knife/DDS/2- Minimal Wear/c_knife.dds"
move 04T.dds "35- Knife/DDS/3- Field-Tested/c_knife.dds"
move 04U.dds "35- Knife/DDS/4- Well-Worn/c_knife.dds"
move 04V.dds "35- Knife/DDS/5- Battle Scarred/c_knife.dds"
move 04W.dds "36- Knife (BLU)/DDS/1- Factory New/c_knife.dds"
move 04X.dds "36- Knife (BLU)/DDS/2- Minimal Wear/c_knife.dds"
move 04Y.dds "36- Knife (BLU)/DDS/3- Field-Tested/c_knife.dds"
move 04Z.dds "36- Knife (BLU)/DDS/4- Well-Worn/c_knife.dds"
move 050.dds "36- Knife (BLU)/DDS/5- Battle Scarred/c_knife.dds"

move 051.dds "37- Loch-n-Load/DDS/1- Factory New/c_lochnload.dds"
move 052.dds "37- Loch-n-Load/DDS/2- Minimal Wear/c_lochnload.dds"
move 053.dds "37- Loch-n-Load/DDS/3- Field-Tested/c_lochnload.dds"
move 054.dds "37- Loch-n-Load/DDS/4- Well-Worn/c_lochnload.dds"
move 055.dds "37- Loch-n-Load/DDS/5- Battle Scarred/c_lochnload.dds"
move 056.dds "38- Loch-n-Load (BLU)/DDS/1- Factory New/c_lochnload.dds"
move 057.dds "38- Loch-n-Load (BLU)/DDS/2- Minimal Wear/c_lochnload.dds"
move 058.dds "38- Loch-n-Load (BLU)/DDS/3- Field-Tested/c_lochnload.dds"
move 059.dds "38- Loch-n-Load (BLU)/DDS/4- Well-Worn/c_lochnload.dds"
move 05A.dds "38- Loch-n-Load (BLU)/DDS/5- Battle Scarred/c_lochnload.dds"

move 05B.dds "39- Loose Cannon/DDS/1- Factory New/c_demo_cannon.dds"
move 05C.dds "39- Loose Cannon/DDS/2- Minimal Wear/c_demo_cannon.dds"
move 05D.dds "39- Loose Cannon/DDS/3- Field-Tested/c_demo_cannon.dds"
move 05E.dds "39- Loose Cannon/DDS/4- Well-Worn/c_demo_cannon.dds"
move 05F.dds "39- Loose Cannon/DDS/5- Battle Scarred/c_demo_cannon.dds"
move 05G.dds "40- Loose Cannon (BLU)/DDS/1- Factory New/c_demo_cannon.dds"
move 05H.dds "40- Loose Cannon (BLU)/DDS/2- Minimal Wear/c_demo_cannon.dds"
move 05I.dds "40- Loose Cannon (BLU)/DDS/3- Field-Tested/c_demo_cannon.dds"
move 05J.dds "40- Loose Cannon (BLU)/DDS/4- Well-Worn/c_demo_cannon.dds"
move 05K.dds "40- Loose Cannon (BLU)/DDS/5- Battle Scarred/c_demo_cannon.dds"

move 05L.dds "41- Medi Gun/DDS/1- Factory New/c_medigun.dds"
move 05M.dds "41- Medi Gun/DDS/2- Minimal Wear/c_medigun.dds"
move 05N.dds "41- Medi Gun/DDS/3- Field-Tested/c_medigun.dds"
move 05O.dds "41- Medi Gun/DDS/4- Well-Worn/c_medigun.dds"
move 05P.dds "41- Medi Gun/DDS/5- Battle Scarred/c_medigun.dds"
move 05Q.dds "42- Medi Gun (BLU)/DDS/1- Factory New/c_medigun_blue.dds"
move 05R.dds "42- Medi Gun (BLU)/DDS/2- Minimal Wear/c_medigun_blue.dds"
move 05S.dds "42- Medi Gun (BLU)/DDS/3- Field-Tested/c_medigun_blue.dds"
move 05T.dds "42- Medi Gun (BLU)/DDS/4- Well-Worn/c_medigun_blue.dds"
move 05U.dds "42- Medi Gun (BLU)/DDS/5- Battle Scarred/c_medigun_blue.dds"

move 05V.dds "43- Minigun/DDS/1- Factory New/c_minigun.dds"
move 05W.dds "43- Minigun/DDS/2- Minimal Wear/c_minigun.dds"
move 05X.dds "43- Minigun/DDS/3- Field-Tested/c_minigun.dds"
move 05Y.dds "43- Minigun/DDS/4- Well-Worn/c_minigun.dds"
move 05Z.dds "43- Minigun/DDS/5- Battle Scarred/c_minigun.dds"
move 060.dds "44- Minigun (BLU)/DDS/1- Factory New/c_minigun.dds"
move 061.dds "44- Minigun (BLU)/DDS/2- Minimal Wear/c_minigun.dds"
move 062.dds "44- Minigun (BLU)/DDS/3- Field-Tested/c_minigun.dds"
move 063.dds "44- Minigun (BLU)/DDS/4- Well-Worn/c_minigun.dds"
move 064.dds "44- Minigun (BLU)/DDS/5- Battle Scarred/c_minigun.dds"

move 065.dds "45- Panic Attack/DDS/1- Factory New/c_trenchgun.dds"
move 066.dds "45- Panic Attack/DDS/2- Minimal Wear/c_trenchgun.dds"
move 067.dds "45- Panic Attack/DDS/3- Field-Tested/c_trenchgun.dds"
move 068.dds "45- Panic Attack/DDS/4- Well-Worn/c_trenchgun.dds"
move 069.dds "45- Panic Attack/DDS/5- Battle Scarred/c_trenchgun.dds"
move 06A.dds "46- Panic Attack (BLU)/DDS/1- Factory New/c_trenchgun.dds"
move 06B.dds "46- Panic Attack (BLU)/DDS/2- Minimal Wear/c_trenchgun.dds"
move 06C.dds "46- Panic Attack (BLU)/DDS/3- Field-Tested/c_trenchgun.dds"
move 06D.dds "46- Panic Attack (BLU)/DDS/4- Well-Worn/c_trenchgun.dds"
move 06E.dds "46- Panic Attack (BLU)/DDS/5- Battle Scarred/c_trenchgun.dds"

move 06F.dds "47- Persian Persuader/DDS/1- Factory New/c_demo_sultan_sword.dds"
move 06G.dds "47- Persian Persuader/DDS/2- Minimal Wear/c_demo_sultan_sword.dds"
move 06H.dds "47- Persian Persuader/DDS/3- Field-Tested/c_demo_sultan_sword.dds"
move 06I.dds "47- Persian Persuader/DDS/4- Well-Worn/c_demo_sultan_sword.dds"
move 06J.dds "47- Persian Persuader/DDS/5- Battle Scarred/c_demo_sultan_sword.dds"
move 06K.dds "48- Persian Persuader (BLU)/DDS/1- Factory New/c_demo_sultan_sword.dds"
move 06L.dds "48- Persian Persuader (BLU)/DDS/2- Minimal Wear/c_demo_sultan_sword.dds"
move 06M.dds "48- Persian Persuader (BLU)/DDS/3- Field-Tested/c_demo_sultan_sword.dds"
move 06N.dds "48- Persian Persuader (BLU)/DDS/4- Well-Worn/c_demo_sultan_sword.dds"
move 06O.dds "48- Persian Persuader (BLU)/DDS/5- Battle Scarred/c_demo_sultan_sword.dds"

move 06P.dds "49- Pistol/DDS/1- Factory New/c_pistol.dds"
move 06Q.dds "49- Pistol/DDS/2- Minimal Wear/c_pistol.dds"
move 06R.dds "49- Pistol/DDS/3- Field-Tested/c_pistol.dds"
move 06S.dds "49- Pistol/DDS/4- Well-Worn/c_pistol.dds"
move 06T.dds "49- Pistol/DDS/5- Battle Scarred/c_pistol.dds"
move 06U.dds "50- Pistol (BLU)/DDS/1- Factory New/c_pistol.dds"
move 06V.dds "50- Pistol (BLU)/DDS/2- Minimal Wear/c_pistol.dds"
move 06W.dds "50- Pistol (BLU)/DDS/3- Field-Tested/c_pistol.dds"
move 06X.dds "50- Pistol (BLU)/DDS/4- Well-Worn/c_pistol.dds"
move 06Y.dds "50- Pistol (BLU)/DDS/5- Battle Scarred/c_pistol.dds"

move 06Z.dds "51- Powerjack/DDS/1- Factory New/c_powerjack_red.dds"
move 070.dds "51- Powerjack/DDS/2- Minimal Wear/c_powerjack_red.dds"
move 071.dds "51- Powerjack/DDS/3- Field-Tested/c_powerjack_red.dds"
move 072.dds "51- Powerjack/DDS/4- Well-Worn/c_powerjack_red.dds"
move 073.dds "51- Powerjack/DDS/5- Battle Scarred/c_powerjack_red.dds"
move 074.dds "52- Powerjack (BLU)/DDS/1- Factory New/c_powerjack_blue.dds"
move 075.dds "52- Powerjack (BLU)/DDS/2- Minimal Wear/c_powerjack_blue.dds"
move 076.dds "52- Powerjack (BLU)/DDS/3- Field-Tested/c_powerjack_blue.dds"
move 077.dds "52- Powerjack (BLU)/DDS/4- Well-Worn/c_powerjack_blue.dds"
move 078.dds "52- Powerjack (BLU)/DDS/5- Battle Scarred/c_powerjack_blue.dds"

move 079.dds "53- Rescue Ranger/DDS/1- Factory New/c_tele_shotgun.dds"
move 07A.dds "53- Rescue Ranger/DDS/2- Minimal Wear/c_tele_shotgun.dds"
move 07B.dds "53- Rescue Ranger/DDS/3- Field-Tested/c_tele_shotgun.dds"
move 07C.dds "53- Rescue Ranger/DDS/4- Well-Worn/c_tele_shotgun.dds"
move 07D.dds "53- Rescue Ranger/DDS/5- Battle Scarred/c_tele_shotgun.dds"
move 07E.dds "54- Rescue Ranger (BLU)/DDS/1- Factory New/c_tele_shotgun_blue.dds"
move 07F.dds "54- Rescue Ranger (BLU)/DDS/2- Minimal Wear/c_tele_shotgun_blue.dds"
move 07G.dds "54- Rescue Ranger (BLU)/DDS/3- Field-Tested/c_tele_shotgun_blue.dds"
move 07H.dds "54- Rescue Ranger (BLU)/DDS/4- Well-Worn/c_tele_shotgun_blue.dds"
move 07I.dds "54- Rescue Ranger (BLU)/DDS/5- Battle Scarred/c_tele_shotgun_blue.dds"

move 07J.dds "55- Reserve Shooter/DDS/1- Factory New/c_reserve_shooter.dds"
move 07K.dds "55- Reserve Shooter/DDS/2- Minimal Wear/c_reserve_shooter.dds"
move 07L.dds "55- Reserve Shooter/DDS/3- Field-Tested/c_reserve_shooter.dds"
move 07M.dds "55- Reserve Shooter/DDS/4- Well-Worn/c_reserve_shooter.dds"
move 07N.dds "55- Reserve Shooter/DDS/5- Battle Scarred/c_reserve_shooter.dds"
move 07O.dds "56- Reserve Shooter (BLU)/DDS/1- Factory New/c_reserve_shooter.dds"
move 07P.dds "56- Reserve Shooter (BLU)/DDS/2- Minimal Wear/c_reserve_shooter.dds"
move 07Q.dds "56- Reserve Shooter (BLU)/DDS/3- Field-Tested/c_reserve_shooter.dds"
move 07R.dds "56- Reserve Shooter (BLU)/DDS/4- Well-Worn/c_reserve_shooter.dds"
move 07S.dds "56- Reserve Shooter (BLU)/DDS/5- Battle Scarred/c_reserve_shooter.dds"

move 07T.dds "57- Revolver/DDS/1- Factory New/c_revolver.dds"
move 07U.dds "57- Revolver/DDS/2- Minimal Wear/c_revolver.dds"
move 07V.dds "57- Revolver/DDS/3- Field-Tested/c_revolver.dds"
move 07W.dds "57- Revolver/DDS/4- Well-Worn/c_revolver.dds"
move 07X.dds "57- Revolver/DDS/5- Battle Scarred/c_revolver.dds"
move 07Y.dds "58- Revolver (BLU)/DDS/1- Factory New/c_revolver.dds"
move 07Z.dds "58- Revolver (BLU)/DDS/2- Minimal Wear/c_revolver.dds"
move 080.dds "58- Revolver (BLU)/DDS/3- Field-Tested/c_revolver.dds"
move 081.dds "58- Revolver (BLU)/DDS/4- Well-Worn/c_revolver.dds"
move 082.dds "58- Revolver (BLU)/DDS/5- Battle Scarred/c_revolver.dds"

move 083.dds "59- Rocket Launcher/DDS/1- Factory New/c_rocketlauncher.dds"
move 084.dds "59- Rocket Launcher/DDS/2- Minimal Wear/c_rocketlauncher.dds"
move 085.dds "59- Rocket Launcher/DDS/3- Field-Tested/c_rocketlauncher.dds"
move 086.dds "59- Rocket Launcher/DDS/4- Well-Worn/c_rocketlauncher.dds"
move 087.dds "59- Rocket Launcher/DDS/5- Battle Scarred/c_rocketlauncher.dds"
move 088.dds "60- Rocket Launcher (BLU)/DDS/1- Factory New/c_rocketlauncher.dds"
move 089.dds "60- Rocket Launcher (BLU)/DDS/2- Minimal Wear/c_rocketlauncher.dds"
move 08A.dds "60- Rocket Launcher (BLU)/DDS/3- Field-Tested/c_rocketlauncher.dds"
move 08B.dds "60- Rocket Launcher (BLU)/DDS/4- Well-Worn/c_rocketlauncher.dds"
move 08C.dds "60- Rocket Launcher (BLU)/DDS/5- Battle Scarred/c_rocketlauncher.dds"

move 08D.dds "61- Scattergun/DDS/1- Factory New/c_scattergun.dds"
move 08E.dds "61- Scattergun/DDS/2- Minimal Wear/c_scattergun.dds"
move 08F.dds "61- Scattergun/DDS/3- Field-Tested/c_scattergun.dds"
move 08G.dds "61- Scattergun/DDS/4- Well-Worn/c_scattergun.dds"
move 08H.dds "61- Scattergun/DDS/5- Battle Scarred/c_scattergun.dds"
move 08I.dds "62- Scattergun (BLU)/DDS/1- Factory New/c_scattergun.dds"
move 08J.dds "62- Scattergun (BLU)/DDS/2- Minimal Wear/c_scattergun.dds"
move 08K.dds "62- Scattergun (BLU)/DDS/3- Field-Tested/c_scattergun.dds"
move 08L.dds "62- Scattergun (BLU)/DDS/4- Well-Worn/c_scattergun.dds"
move 08M.dds "62- Scattergun (BLU)/DDS/5- Battle Scarred/c_scattergun.dds"

move 08N.dds "63- Scorch Shot/DDS/1- Factory New/c_scorch_shot.dds"
move 08O.dds "63- Scorch Shot/DDS/2- Minimal Wear/c_scorch_shot.dds"
move 08P.dds "63- Scorch Shot/DDS/3- Field-Tested/c_scorch_shot.dds"
move 08Q.dds "63- Scorch Shot/DDS/4- Well-Worn/c_scorch_shot.dds"
move 08R.dds "63- Scorch Shot/DDS/5- Battle Scarred/c_scorch_shot.dds"
move 08S.dds "64- Scorch Shot (BLU)/DDS/1- Factory New/c_scorch_shot_blue.dds"
move 08T.dds "64- Scorch Shot (BLU)/DDS/2- Minimal Wear/c_scorch_shot_blue.dds"
move 08U.dds "64- Scorch Shot (BLU)/DDS/3- Field-Tested/c_scorch_shot_blue.dds"
move 08V.dds "64- Scorch Shot (BLU)/DDS/4- Well-Worn/c_scorch_shot_blue.dds"
move 08W.dds "64- Scorch Shot (BLU)/DDS/5- Battle Scarred/c_scorch_shot_blue.dds"

move 08X.dds "65- Scotsman's Skullcutter/DDS/1- Factory New/c_battleaxe.dds"
move 08Y.dds "65- Scotsman's Skullcutter/DDS/2- Minimal Wear/c_battleaxe.dds"
move 08Z.dds "65- Scotsman's Skullcutter/DDS/3- Field-Tested/c_battleaxe.dds"
move 090.dds "65- Scotsman's Skullcutter/DDS/4- Well-Worn/c_battleaxe.dds"
move 091.dds "65- Scotsman's Skullcutter/DDS/5- Battle Scarred/c_battleaxe.dds"
move 092.dds "66- Scotsman's Skullcutter (BLU)/DDS/1- Factory New/c_battleaxe.dds"
move 093.dds "66- Scotsman's Skullcutter (BLU)/DDS/2- Minimal Wear/c_battleaxe.dds"
move 094.dds "66- Scotsman's Skullcutter (BLU)/DDS/3- Field-Tested/c_battleaxe.dds"
move 095.dds "66- Scotsman's Skullcutter (BLU)/DDS/4- Well-Worn/c_battleaxe.dds"
move 096.dds "66- Scotsman's Skullcutter (BLU)/DDS/5- Battle Scarred/c_battleaxe.dds"

move 097.dds "67- Shahanshah/DDS/1- Factory New/c_scimitar.dds"
move 098.dds "67- Shahanshah/DDS/2- Minimal Wear/c_scimitar.dds"
move 099.dds "67- Shahanshah/DDS/3- Field-Tested/c_scimitar.dds"
move 09A.dds "67- Shahanshah/DDS/4- Well-Worn/c_scimitar.dds"
move 09B.dds "67- Shahanshah/DDS/5- Battle Scarred/c_scimitar.dds"
move 09C.dds "68- Shahanshah (BLU)/DDS/1- Factory New/c_scimitar.dds"
move 09D.dds "68- Shahanshah (BLU)/DDS/2- Minimal Wear/c_scimitar.dds"
move 09E.dds "68- Shahanshah (BLU)/DDS/3- Field-Tested/c_scimitar.dds"
move 09F.dds "68- Shahanshah (BLU)/DDS/4- Well-Worn/c_scimitar.dds"
move 09G.dds "68- Shahanshah (BLU)/DDS/5- Battle Scarred/c_scimitar.dds"

move 09H.dds "69- Shortstop/DDS/1- Factory New/c_shortstop.dds"
move 09I.dds "69- Shortstop/DDS/2- Minimal Wear/c_shortstop.dds"
move 09J.dds "69- Shortstop/DDS/3- Field-Tested/c_shortstop.dds"
move 09K.dds "69- Shortstop/DDS/4- Well-Worn/c_shortstop.dds"
move 09L.dds "69- Shortstop/DDS/5- Battle Scarred/c_shortstop.dds"
move 09M.dds "70- Shortstop (BLU)/DDS/1- Factory New/c_shortstop.dds"
move 09N.dds "70- Shortstop (BLU)/DDS/2- Minimal Wear/c_shortstop.dds"
move 09O.dds "70- Shortstop (BLU)/DDS/3- Field-Tested/c_shortstop.dds"
move 09P.dds "70- Shortstop (BLU)/DDS/4- Well-Worn/c_shortstop.dds"
move 09Q.dds "70- Shortstop (BLU)/DDS/5- Battle Scarred/c_shortstop.dds"

move 09R.dds "71- Shotgun/DDS/1- Factory New/c_shotgun.dds"
move 09S.dds "71- Shotgun/DDS/2- Minimal Wear/c_shotgun.dds"
move 09T.dds "71- Shotgun/DDS/3- Field-Tested/c_shotgun.dds"
move 09U.dds "71- Shotgun/DDS/4- Well-Worn/c_shotgun.dds"
move 09V.dds "71- Shotgun/DDS/5- Battle Scarred/c_shotgun.dds"
move 09W.dds "72- Shotgun (BLU)/DDS/1- Factory New/c_shotgun.dds"
move 09X.dds "72- Shotgun (BLU)/DDS/2- Minimal Wear/c_shotgun.dds"
move 09Y.dds "72- Shotgun (BLU)/DDS/3- Field-Tested/c_shotgun.dds"
move 09Z.dds "72- Shotgun (BLU)/DDS/4- Well-Worn/c_shotgun.dds"
move 0A0.dds "72- Shotgun (BLU)/DDS/5- Battle Scarred/c_shotgun.dds"

move 0A1.dds "73- Submachine Gun/DDS/1- Factory New/c_smg.dds"
move 0A2.dds "73- Submachine Gun/DDS/2- Minimal Wear/c_smg.dds"
move 0A3.dds "73- Submachine Gun/DDS/3- Field-Tested/c_smg.dds"
move 0A4.dds "73- Submachine Gun/DDS/4- Well-Worn/c_smg.dds"
move 0A5.dds "73- Submachine Gun/DDS/5- Battle Scarred/c_smg.dds"
move 0A6.dds "74- Submachine Gun (BLU)/DDS/1- Factory New/c_smg.dds"
move 0A7.dds "74- Submachine Gun (BLU)/DDS/2- Minimal Wear/c_smg.dds"
move 0A8.dds "74- Submachine Gun (BLU)/DDS/3- Field-Tested/c_smg.dds"
move 0A9.dds "74- Submachine Gun (BLU)/DDS/4- Well-Worn/c_smg.dds"
move 0AA.dds "74- Submachine Gun (BLU)/DDS/5- Battle Scarred/c_smg.dds"

move 0AB.dds "75- Sniper Rifle/DDS/1- Factory New/c_sniperrifle.dds"
move 0AC.dds "75- Sniper Rifle/DDS/2- Minimal Wear/c_sniperrifle.dds"
move 0AD.dds "75- Sniper Rifle/DDS/3- Field-Tested/c_sniperrifle.dds"
move 0AE.dds "75- Sniper Rifle/DDS/4- Well-Worn/c_sniperrifle.dds"
move 0AF.dds "75- Sniper Rifle/DDS/5- Battle Scarred/c_sniperrifle.dds"
move 0AG.dds "76- Sniper Rifle (BLU)/DDS/1- Factory New/c_sniperrifle.dds"
move 0AH.dds "76- Sniper Rifle (BLU)/DDS/2- Minimal Wear/c_sniperrifle.dds"
move 0AI.dds "76- Sniper Rifle (BLU)/DDS/3- Field-Tested/c_sniperrifle.dds"
move 0AJ.dds "76- Sniper Rifle (BLU)/DDS/4- Well-Worn/c_sniperrifle.dds"
move 0AK.dds "76- Sniper Rifle (BLU)/DDS/5- Battle Scarred/c_sniperrifle.dds"

move 0AL.dds "77- Soda Popper/DDS/1- Factory New/c_soda_popper.dds"
move 0AM.dds "77- Soda Popper/DDS/2- Minimal Wear/c_soda_popper.dds"
move 0AN.dds "77- Soda Popper/DDS/3- Field-Tested/c_soda_popper.dds"
move 0AO.dds "77- Soda Popper/DDS/4- Well-Worn/c_soda_popper.dds"
move 0AP.dds "77- Soda Popper/DDS/5- Battle Scarred/c_soda_popper.dds"
move 0AQ.dds "78- Soda Popper (BLU)/DDS/1- Factory New/c_soda_popper.dds"
move 0AR.dds "78- Soda Popper (BLU)/DDS/2- Minimal Wear/c_soda_popper.dds"
move 0AS.dds "78- Soda Popper (BLU)/DDS/3- Field-Tested/c_soda_popper.dds"
move 0AT.dds "78- Soda Popper (BLU)/DDS/4- Well-Worn/c_soda_popper.dds"
move 0AU.dds "78- Soda Popper (BLU)/DDS/5- Battle Scarred/c_soda_popper.dds"

move 0AV.dds "79- Stickybomb Launcher/DDS/1- Factory New/c_stickybomb_launcher.dds"
move 0AW.dds "79- Stickybomb Launcher/DDS/2- Minimal Wear/c_stickybomb_launcher.dds"
move 0AX.dds "79- Stickybomb Launcher/DDS/3- Field-Tested/c_stickybomb_launcher.dds"
move 0AY.dds "79- Stickybomb Launcher/DDS/4- Well-Worn/c_stickybomb_launcher.dds"
move 0AZ.dds "79- Stickybomb Launcher/DDS/5- Battle Scarred/c_stickybomb_launcher.dds"
move 0B0.dds "80- Stickybomb Launcher (BLU)/DDS/1- Factory New/c_stickybomb_launcher.dds"
move 0B1.dds "80- Stickybomb Launcher (BLU)/DDS/2- Minimal Wear/c_stickybomb_launcher.dds"
move 0B2.dds "80- Stickybomb Launcher (BLU)/DDS/3- Field-Tested/c_stickybomb_launcher.dds"
move 0B3.dds "80- Stickybomb Launcher (BLU)/DDS/4- Well-Worn/c_stickybomb_launcher.dds"
move 0B4.dds "80- Stickybomb Launcher (BLU)/DDS/5- Battle Scarred/c_stickybomb_launcher.dds"

move 0B5.dds "81- Tomislav/DDS/1- Factory New/c_tomislav.dds"
move 0B6.dds "81- Tomislav/DDS/2- Minimal Wear/c_tomislav.dds"
move 0B7.dds "81- Tomislav/DDS/3- Field-Tested/c_tomislav.dds"
move 0B8.dds "81- Tomislav/DDS/4- Well-Worn/c_tomislav.dds"
move 0B9.dds "81- Tomislav/DDS/5- Battle Scarred/c_tomislav.dds"
move 0BA.dds "82- Tomislav (BLU)/DDS/1- Factory New/c_tomislav.dds"
move 0BB.dds "82- Tomislav (BLU)/DDS/2- Minimal Wear/c_tomislav.dds"
move 0BC.dds "82- Tomislav (BLU)/DDS/3- Field-Tested/c_tomislav.dds"
move 0BD.dds "82- Tomislav (BLU)/DDS/4- Well-Worn/c_tomislav.dds"
move 0BE.dds "82- Tomislav (BLU)/DDS/5- Battle Scarred/c_tomislav.dds"

move 0BF.dds "83- Ubersaw/DDS/1- Factory New/c_ubersaw.dds"
move 0BG.dds "83- Ubersaw/DDS/2- Minimal Wear/c_ubersaw.dds"
move 0BH.dds "83- Ubersaw/DDS/3- Field-Tested/c_ubersaw.dds"
move 0BI.dds "83- Ubersaw/DDS/4- Well-Worn/c_ubersaw.dds"
move 0BJ.dds "83- Ubersaw/DDS/5- Battle Scarred/c_ubersaw.dds"
move 0BK.dds "84- Ubersaw (BLU)/DDS/1- Factory New/c_ubersaw.dds"
move 0BL.dds "84- Ubersaw (BLU)/DDS/2- Minimal Wear/c_ubersaw.dds"
move 0BM.dds "84- Ubersaw (BLU)/DDS/3- Field-Tested/c_ubersaw.dds"
move 0BN.dds "84- Ubersaw (BLU)/DDS/4- Well-Worn/c_ubersaw.dds"
move 0BO.dds "84- Ubersaw (BLU)/DDS/5- Battle Scarred/c_ubersaw.dds"

move 0BP.dds "85- War Paint/DDS/1- Factory New/paintkit_tool.dds"
move 0BQ.dds "85- War Paint/DDS/2- Minimal Wear/paintkit_tool.dds"
move 0BR.dds "85- War Paint/DDS/3- Field-Tested/paintkit_tool.dds"
move 0BS.dds "85- War Paint/DDS/4- Well-Worn/paintkit_tool.dds"
move 0BT.dds "85- War Paint/DDS/5- Battle Scarred/paintkit_tool.dds"
move 0BU.dds "86- War Paint (BLU)/DDS/1- Factory New/paintkit_tool.dds"
move 0BV.dds "86- War Paint (BLU)/DDS/2- Minimal Wear/paintkit_tool.dds"
move 0BW.dds "86- War Paint (BLU)/DDS/3- Field-Tested/paintkit_tool.dds"
move 0BX.dds "86- War Paint (BLU)/DDS/4- Well-Worn/paintkit_tool.dds"
move 0BY.dds "86- War Paint (BLU)/DDS/5- Battle Scarred/paintkit_tool.dds"

move 0BZ.dds "87- Winger/DDS/1- Factory New/c_winger_pistol.dds"
move 0C0.dds "87- Winger/DDS/2- Minimal Wear/c_winger_pistol.dds"
move 0C1.dds "87- Winger/DDS/3- Field-Tested/c_winger_pistol.dds"
move 0C2.dds "87- Winger/DDS/4- Well-Worn/c_winger_pistol.dds"
move 0C3.dds "87- Winger/DDS/5- Battle Scarred/c_winger_pistol.dds"
move 0C4.dds "88- Winger (BLU)/DDS/1- Factory New/c_winger_pistol.dds"
move 0C5.dds "88- Winger (BLU)/DDS/2- Minimal Wear/c_winger_pistol.dds"
move 0C6.dds "88- Winger (BLU)/DDS/3- Field-Tested/c_winger_pistol.dds"
move 0C7.dds "88- Winger (BLU)/DDS/4- Well-Worn/c_winger_pistol.dds"
move 0C8.dds "88- Winger (BLU)/DDS/5- Battle Scarred/c_winger_pistol.dds"

move 0C9.dds "89- Wrench/DDS/1- Factory New/c_wrench.dds"
move 0CA.dds "89- Wrench/DDS/2- Minimal Wear/c_wrench.dds"
move 0CB.dds "89- Wrench/DDS/3- Field-Tested/c_wrench.dds"
move 0CC.dds "89- Wrench/DDS/4- Well-Worn/c_wrench.dds"
move 0CD.dds "89- Wrench/DDS/5- Battle Scarred/c_wrench.dds"
move 0CE.dds "90- Wrench (BLU)/DDS/1- Factory New/c_wrench.dds"
move 0CF.dds "90- Wrench (BLU)/DDS/2- Minimal Wear/c_wrench.dds"
move 0CG.dds "90- Wrench (BLU)/DDS/3- Field-Tested/c_wrench.dds"
move 0CH.dds "90- Wrench (BLU)/DDS/4- Well-Worn/c_wrench.dds"
move 0CI.dds "90- Wrench (BLU)/DDS/5- Battle Scarred/c_wrench.dds"