move 001.dds "1- Air Strike/DDS/1- Factory New/c_atom_launcher.dds"
move 002.dds "1- Air Strike/DDS/2- Minimal Wear/c_atom_launcher.dds"
move 003.dds "1- Air Strike/DDS/3- Field-Tested/c_atom_launcher.dds"
move 004.dds "1- Air Strike/DDS/4- Well-Worn/c_atom_launcher.dds"
move 005.dds "1- Air Strike/DDS/5- Battle Scarred/c_atom_launcher.dds"

move 006.dds "2- Amputator/DDS/1- Factory New/c_amputator.dds"
move 007.dds "2- Amputator/DDS/2- Minimal Wear/c_amputator.dds"
move 008.dds "2- Amputator/DDS/3- Field-Tested/c_amputator.dds"
move 009.dds "2- Amputator/DDS/4- Well-Worn/c_amputator.dds"
move 00A.dds "2- Amputator/DDS/5- Battle Scarred/c_amputator.dds"

move 00B.dds "3- Back Scratcher/DDS/1- Factory New/c_back_scratcher.dds"
move 00C.dds "3- Back Scratcher/DDS/2- Minimal Wear/c_back_scratcher.dds"
move 00D.dds "3- Back Scratcher/DDS/3- Field-Tested/c_back_scratcher.dds"
move 00E.dds "3- Back Scratcher/DDS/4- Well-Worn/c_back_scratcher.dds"
move 00F.dds "3- Back Scratcher/DDS/5- Battle Scarred/c_back_scratcher.dds"

move 00G.dds "4- Bazaar Bargain/DDS/1- Factory New/c_bazaar_sniper.dds"
move 00H.dds "4- Bazaar Bargain/DDS/2- Minimal Wear/c_bazaar_sniper.dds"
move 00I.dds "4- Bazaar Bargain/DDS/3- Field-Tested/c_bazaar_sniper.dds"
move 00J.dds "4- Bazaar Bargain/DDS/4- Well-Worn/c_bazaar_sniper.dds"
move 00K.dds "4- Bazaar Bargain/DDS/5- Battle Scarred/c_bazaar_sniper.dds"

move 00L.dds "5- Black Box/DDS/1- Factory New/c_blackbox.dds"
move 00M.dds "5- Black Box/DDS/2- Minimal Wear/c_blackbox.dds"
move 00N.dds "5- Black Box/DDS/3- Field-Tested/c_blackbox.dds"
move 00O.dds "5- Black Box/DDS/4- Well-Worn/c_blackbox.dds"
move 00P.dds "5- Black Box/DDS/5- Battle Scarred/c_blackbox.dds"

move 00Q.dds "6- Brass Beast/DDS/1- Factory New/c_gatling_gun.dds"
move 00R.dds "6- Brass Beast/DDS/2- Minimal Wear/c_gatling_gun.dds"
move 00S.dds "6- Brass Beast/DDS/3- Field-Tested/c_gatling_gun.dds"
move 00T.dds "6- Brass Beast/DDS/4- Well-Worn/c_gatling_gun.dds"
move 00U.dds "6- Brass Beast/DDS/5- Battle Scarred/c_gatling_gun.dds"

move 00V.dds "7- Claidheamh Mor/DDS/1- Factory New/c_claidheamohmor.dds"
move 00W.dds "7- Claidheamh Mor/DDS/2- Minimal Wear/c_claidheamohmor.dds"
move 00X.dds "7- Claidheamh Mor/DDS/3- Field-Tested/c_claidheamohmor.dds"
move 00Y.dds "7- Claidheamh Mor/DDS/4- Well-Worn/c_claidheamohmor.dds"
move 00Z.dds "7- Claidheamh Mor/DDS/5- Battle Scarred/c_claidheamohmor.dds"

move 010.dds "8- Crusader's Crossbow/DDS/1- Factory New/c_crusaders_crossbow.dds"
move 011.dds "8- Crusader's Crossbow/DDS/2- Minimal Wear/c_crusaders_crossbow.dds"
move 012.dds "8- Crusader's Crossbow/DDS/3- Field-Tested/c_crusaders_crossbow.dds"
move 013.dds "8- Crusader's Crossbow/DDS/4- Well-Worn/c_crusaders_crossbow.dds"
move 014.dds "8- Crusader's Crossbow/DDS/5- Battle Scarred/c_crusaders_crossbow.dds"

move 015.dds "9- Degreaser/DDS/1- Factory New/c_degreaser_red.dds"
move 016.dds "9- Degreaser/DDS/2- Minimal Wear/c_degreaser_red.dds"
move 017.dds "9- Degreaser/DDS/3- Field-Tested/c_degreaser_red.dds"
move 018.dds "9- Degreaser/DDS/4- Well-Worn/c_degreaser_red.dds"
move 019.dds "9- Degreaser/DDS/5- Battle Scarred/c_degreaser_red.dds"

move 01A.dds "10- Detonator/DDS/1- Factory New/c_detonator.dds"
move 01B.dds "10- Detonator/DDS/2- Minimal Wear/c_detonator.dds"
move 01C.dds "10- Detonator/DDS/3- Field-Tested/c_detonator.dds"
move 01D.dds "10- Detonator/DDS/4- Well-Worn/c_detonator.dds"
move 01E.dds "10- Detonator/DDS/5- Battle Scarred/c_detonator.dds"

move 01F.dds "11- Disciplinary Action/DDS/1- Factory New/c_riding_crop.dds"
move 01G.dds "11- Disciplinary Action/DDS/2- Minimal Wear/c_riding_crop.dds"
move 01H.dds "11- Disciplinary Action/DDS/3- Field-Tested/c_riding_crop.dds"
move 01I.dds "11- Disciplinary Action/DDS/4- Well-Worn/c_riding_crop.dds"
move 01J.dds "11- Disciplinary Action/DDS/5- Battle Scarred/c_riding_crop.dds"

move 01K.dds "12- Family Business/DDS/1- Factory New/c_russian_riot.dds"
move 01L.dds "12- Family Business/DDS/2- Minimal Wear/c_russian_riot.dds"
move 01M.dds "12- Family Business/DDS/3- Field-Tested/c_russian_riot.dds"
move 01N.dds "12- Family Business/DDS/4- Well-Worn/c_russian_riot.dds"
move 01O.dds "12- Family Business/DDS/5- Battle Scarred/c_russian_riot.dds"

move 01P.dds "13- Flame Thrower/DDS/1- Factory New/c_flamethrower.dds"
move 01Q.dds "13- Flame Thrower/DDS/2- Minimal Wear/c_flamethrower.dds"
move 01R.dds "13- Flame Thrower/DDS/3- Field-Tested/c_flamethrower.dds"
move 01S.dds "13- Flame Thrower/DDS/4- Well-Worn/c_flamethrower.dds"
move 01T.dds "13- Flame Thrower/DDS/5- Battle Scarred/c_flamethrower.dds"

move 01U.dds "14- Grenade Launcher/DDS/1- Factory New/c_grenadelauncher.dds"
move 01V.dds "14- Grenade Launcher/DDS/2- Minimal Wear/c_grenadelauncher.dds"
move 01W.dds "14- Grenade Launcher/DDS/3- Field-Tested/c_grenadelauncher.dds"
move 01X.dds "14- Grenade Launcher/DDS/4- Well-Worn/c_grenadelauncher.dds"
move 01Y.dds "14- Grenade Launcher/DDS/5- Battle Scarred/c_grenadelauncher.dds"

move 01Z.dds "15- Holy Mackerel/DDS/1- Factory New/c_holymackerel.dds"
move 020.dds "15- Holy Mackerel/DDS/2- Minimal Wear/c_holymackerel.dds"
move 021.dds "15- Holy Mackerel/DDS/3- Field-Tested/c_holymackerel.dds"
move 022.dds "15- Holy Mackerel/DDS/4- Well-Worn/c_holymackerel.dds"
move 023.dds "15- Holy Mackerel/DDS/5- Battle Scarred/c_holymackerel.dds"

move 024.dds "17- Iron Bomber/DDS/1- Factory New/c_quadball.dds"
move 025.dds "17- Iron Bomber/DDS/2- Minimal Wear/c_quadball.dds"
move 026.dds "17- Iron Bomber/DDS/3- Field-Tested/c_quadball.dds"
move 027.dds "17- Iron Bomber/DDS/4- Well-Worn/c_quadball.dds"
move 028.dds "17- Iron Bomber/DDS/5- Battle Scarred/c_quadball.dds"

move 029.dds "18- Jag/DDS/1- Factory New/c_jag.dds"
move 02A.dds "18- Jag/DDS/2- Minimal Wear/c_jag.dds"
move 02B.dds "18- Jag/DDS/3- Field-Tested/c_jag.dds"
move 02C.dds "18- Jag/DDS/4- Well-Worn/c_jag.dds"
move 02D.dds "18- Jag/DDS/5- Battle Scarred/c_jag.dds"

move 02E.dds "19- Knife/DDS/1- Factory New/c_knife.dds"
move 02F.dds "19- Knife/DDS/2- Minimal Wear/c_knife.dds"
move 02G.dds "19- Knife/DDS/3- Field-Tested/c_knife.dds"
move 02H.dds "19- Knife/DDS/4- Well-Worn/c_knife.dds"
move 02I.dds "19- Knife/DDS/5- Battle Scarred/c_knife.dds"

move 02J.dds "20- Loch-n-Load/DDS/1- Factory New/c_lochnload.dds"
move 02K.dds "20- Loch-n-Load/DDS/2- Minimal Wear/c_lochnload.dds"
move 02L.dds "20- Loch-n-Load/DDS/3- Field-Tested/c_lochnload.dds"
move 02M.dds "20- Loch-n-Load/DDS/4- Well-Worn/c_lochnload.dds"
move 02N.dds "20- Loch-n-Load/DDS/5- Battle Scarred/c_lochnload.dds"

move 02O.dds "21- Loose Cannon/DDS/1- Factory New/c_demo_cannon.dds"
move 02P.dds "21- Loose Cannon/DDS/2- Minimal Wear/c_demo_cannon.dds"
move 02Q.dds "21- Loose Cannon/DDS/3- Field-Tested/c_demo_cannon.dds"
move 02R.dds "21- Loose Cannon/DDS/4- Well-Worn/c_demo_cannon.dds"
move 02S.dds "21- Loose Cannon/DDS/5- Battle Scarred/c_demo_cannon.dds"

move 02T.dds "22- Medi Gun/DDS/1- Factory New/c_medigun.dds"
move 02U.dds "22- Medi Gun/DDS/2- Minimal Wear/c_medigun.dds"
move 02V.dds "22- Medi Gun/DDS/3- Field-Tested/c_medigun.dds"
move 02W.dds "22- Medi Gun/DDS/4- Well-Worn/c_medigun.dds"
move 02X.dds "22- Medi Gun/DDS/5- Battle Scarred/c_medigun.dds"

move 02Y.dds "23- Minigun/DDS/1- Factory New/c_minigun.dds"
move 02Z.dds "23- Minigun/DDS/2- Minimal Wear/c_minigun.dds"
move 030.dds "23- Minigun/DDS/3- Field-Tested/c_minigun.dds"
move 031.dds "23- Minigun/DDS/4- Well-Worn/c_minigun.dds"
move 032.dds "23- Minigun/DDS/5- Battle Scarred/c_minigun.dds"

move 033.dds "24- Panic Attack/DDS/1- Factory New/c_trenchgun.dds"
move 034.dds "24- Panic Attack/DDS/2- Minimal Wear/c_trenchgun.dds"
move 035.dds "24- Panic Attack/DDS/3- Field-Tested/c_trenchgun.dds"
move 036.dds "24- Panic Attack/DDS/4- Well-Worn/c_trenchgun.dds"
move 037.dds "24- Panic Attack/DDS/5- Battle Scarred/c_trenchgun.dds"

move 038.dds "25- Persian Persuader/DDS/1- Factory New/c_demo_sultan_sword.dds"
move 039.dds "25- Persian Persuader/DDS/2- Minimal Wear/c_demo_sultan_sword.dds"
move 03A.dds "25- Persian Persuader/DDS/3- Field-Tested/c_demo_sultan_sword.dds"
move 03B.dds "25- Persian Persuader/DDS/4- Well-Worn/c_demo_sultan_sword.dds"
move 03C.dds "25- Persian Persuader/DDS/5- Battle Scarred/c_demo_sultan_sword.dds"

move 03D.dds "26- Pistol/DDS/1- Factory New/c_pistol.dds"
move 03E.dds "26- Pistol/DDS/2- Minimal Wear/c_pistol.dds"
move 03F.dds "26- Pistol/DDS/3- Field-Tested/c_pistol.dds"
move 03G.dds "26- Pistol/DDS/4- Well-Worn/c_pistol.dds"
move 03H.dds "26- Pistol/DDS/5- Battle Scarred/c_pistol.dds"

move 03I.dds "27- Powerjack/DDS/1- Factory New/c_powerjack_red.dds"
move 03J.dds "27- Powerjack/DDS/2- Minimal Wear/c_powerjack_red.dds"
move 03K.dds "27- Powerjack/DDS/3- Field-Tested/c_powerjack_red.dds"
move 03L.dds "27- Powerjack/DDS/4- Well-Worn/c_powerjack_red.dds"
move 03M.dds "27- Powerjack/DDS/5- Battle Scarred/c_powerjack_red.dds"

move 03N.dds "28- Rescue Ranger/DDS/1- Factory New/c_tele_shotgun.dds"
move 03O.dds "28- Rescue Ranger/DDS/2- Minimal Wear/c_tele_shotgun.dds"
move 03P.dds "28- Rescue Ranger/DDS/3- Field-Tested/c_tele_shotgun.dds"
move 03Q.dds "28- Rescue Ranger/DDS/4- Well-Worn/c_tele_shotgun.dds"
move 03R.dds "28- Rescue Ranger/DDS/5- Battle Scarred/c_tele_shotgun.dds"

move 03S.dds "30- Reserve Shooter/DDS/1- Factory New/c_reserve_shooter.dds"
move 03T.dds "30- Reserve Shooter/DDS/2- Minimal Wear/c_reserve_shooter.dds"
move 03U.dds "30- Reserve Shooter/DDS/3- Field-Tested/c_reserve_shooter.dds"
move 03V.dds "30- Reserve Shooter/DDS/4- Well-Worn/c_reserve_shooter.dds"
move 03W.dds "30- Reserve Shooter/DDS/5- Battle Scarred/c_reserve_shooter.dds"

move 03X.dds "31- Revolver/DDS/1- Factory New/c_revolver.dds"
move 03Y.dds "31- Revolver/DDS/2- Minimal Wear/c_revolver.dds"
move 03Z.dds "31- Revolver/DDS/3- Field-Tested/c_revolver.dds"
move 040.dds "31- Revolver/DDS/4- Well-Worn/c_revolver.dds"
move 041.dds "31- Revolver/DDS/5- Battle Scarred/c_revolver.dds"

move 042.dds "32- Rocket Launcher/DDS/1- Factory New/c_rocketlauncher.dds"
move 043.dds "32- Rocket Launcher/DDS/2- Minimal Wear/c_rocketlauncher.dds"
move 044.dds "32- Rocket Launcher/DDS/3- Field-Tested/c_rocketlauncher.dds"
move 045.dds "32- Rocket Launcher/DDS/4- Well-Worn/c_rocketlauncher.dds"
move 046.dds "32- Rocket Launcher/DDS/5- Battle Scarred/c_rocketlauncher.dds"

move 047.dds "33- Scattergun/DDS/1- Factory New/c_scattergun.dds"
move 048.dds "33- Scattergun/DDS/2- Minimal Wear/c_scattergun.dds"
move 049.dds "33- Scattergun/DDS/3- Field-Tested/c_scattergun.dds"
move 04A.dds "33- Scattergun/DDS/4- Well-Worn/c_scattergun.dds"
move 04B.dds "33- Scattergun/DDS/5- Battle Scarred/c_scattergun.dds"

move 04C.dds "34- Scorch Shot/DDS/1- Factory New/c_scorch_shot.dds"
move 04D.dds "34- Scorch Shot/DDS/2- Minimal Wear/c_scorch_shot.dds"
move 04E.dds "34- Scorch Shot/DDS/3- Field-Tested/c_scorch_shot.dds"
move 04F.dds "34- Scorch Shot/DDS/4- Well-Worn/c_scorch_shot.dds"
move 04G.dds "34- Scorch Shot/DDS/5- Battle Scarred/c_scorch_shot.dds"

move 04H.dds "35- Scotsman's Skullcutter/DDS/1- Factory New/c_battleaxe.dds"
move 04I.dds "35- Scotsman's Skullcutter/DDS/2- Minimal Wear/c_battleaxe.dds"
move 04J.dds "35- Scotsman's Skullcutter/DDS/3- Field-Tested/c_battleaxe.dds"
move 04K.dds "35- Scotsman's Skullcutter/DDS/4- Well-Worn/c_battleaxe.dds"
move 04L.dds "35- Scotsman's Skullcutter/DDS/5- Battle Scarred/c_battleaxe.dds"

move 04M.dds "36- Shahanshah/DDS/1- Factory New/c_scimitar.dds"
move 04N.dds "36- Shahanshah/DDS/2- Minimal Wear/c_scimitar.dds"
move 04O.dds "36- Shahanshah/DDS/3- Field-Tested/c_scimitar.dds"
move 04P.dds "36- Shahanshah/DDS/4- Well-Worn/c_scimitar.dds"
move 04Q.dds "36- Shahanshah/DDS/5- Battle Scarred/c_scimitar.dds"

move 04R.dds "37- Shortstop/DDS/1- Factory New/c_shortstop.dds"
move 04S.dds "37- Shortstop/DDS/2- Minimal Wear/c_shortstop.dds"
move 04T.dds "37- Shortstop/DDS/3- Field-Tested/c_shortstop.dds"
move 04U.dds "37- Shortstop/DDS/4- Well-Worn/c_shortstop.dds"
move 04V.dds "37- Shortstop/DDS/5- Battle Scarred/c_shortstop.dds"

move 04W.dds "38- Shotgun/DDS/1- Factory New/c_shotgun.dds"
move 04X.dds "38- Shotgun/DDS/2- Minimal Wear/c_shotgun.dds"
move 04Y.dds "38- Shotgun/DDS/3- Field-Tested/c_shotgun.dds"
move 04Z.dds "38- Shotgun/DDS/4- Well-Worn/c_shotgun.dds"
move 050.dds "38- Shotgun/DDS/5- Battle Scarred/c_shotgun.dds"

move 051.dds "39- Submachine Gun/DDS/1- Factory New/c_smg.dds"
move 052.dds "39- Submachine Gun/DDS/2- Minimal Wear/c_smg.dds"
move 053.dds "39- Submachine Gun/DDS/3- Field-Tested/c_smg.dds"
move 054.dds "39- Submachine Gun/DDS/4- Well-Worn/c_smg.dds"
move 055.dds "39- Submachine Gun/DDS/5- Battle Scarred/c_smg.dds"

move 056.dds "40- Sniper Rifle/DDS/1- Factory New/c_sniperrifle.dds"
move 057.dds "40- Sniper Rifle/DDS/2- Minimal Wear/c_sniperrifle.dds"
move 058.dds "40- Sniper Rifle/DDS/3- Field-Tested/c_sniperrifle.dds"
move 059.dds "40- Sniper Rifle/DDS/4- Well-Worn/c_sniperrifle.dds"
move 05A.dds "40- Sniper Rifle/DDS/5- Battle Scarred/c_sniperrifle.dds"

move 05B.dds "41- Soda Popper/DDS/1- Factory New/c_soda_popper.dds"
move 05C.dds "41- Soda Popper/DDS/2- Minimal Wear/c_soda_popper.dds"
move 05D.dds "41- Soda Popper/DDS/3- Field-Tested/c_soda_popper.dds"
move 05E.dds "41- Soda Popper/DDS/4- Well-Worn/c_soda_popper.dds"
move 05F.dds "41- Soda Popper/DDS/5- Battle Scarred/c_soda_popper.dds"

move 05G.dds "42- Stickybomb Launcher/DDS/1- Factory New/c_stickybomb_launcher.dds"
move 05H.dds "42- Stickybomb Launcher/DDS/2- Minimal Wear/c_stickybomb_launcher.dds"
move 05I.dds "42- Stickybomb Launcher/DDS/3- Field-Tested/c_stickybomb_launcher.dds"
move 05J.dds "42- Stickybomb Launcher/DDS/4- Well-Worn/c_stickybomb_launcher.dds"
move 05K.dds "42- Stickybomb Launcher/DDS/5- Battle Scarred/c_stickybomb_launcher.dds"

move 05L.dds "43- Tomislav/DDS/1- Factory New/c_tomislav.dds"
move 05M.dds "43- Tomislav/DDS/2- Minimal Wear/c_tomislav.dds"
move 05N.dds "43- Tomislav/DDS/3- Field-Tested/c_tomislav.dds"
move 05O.dds "43- Tomislav/DDS/4- Well-Worn/c_tomislav.dds"
move 05P.dds "43- Tomislav/DDS/5- Battle Scarred/c_tomislav.dds"

copy 05Q.dds "44- Ubersaw/DDS/1- Factory New/c_ubersaw.dds"
copy 05R.dds "44- Ubersaw/DDS/2- Minimal Wear/c_ubersaw.dds"
copy 05S.dds "44- Ubersaw/DDS/3- Field-Tested/c_ubersaw.dds"
copy 05T.dds "44- Ubersaw/DDS/4- Well-Worn/c_ubersaw.dds"
copy 05U.dds "44- Ubersaw/DDS/5- Battle Scarred/c_ubersaw.dds"

move 05Q.dds "45- Ubersaw (BLU)/DDS/1- Factory New/c_ubersaw.dds"
move 05R.dds "45- Ubersaw (BLU)/DDS/2- Minimal Wear/c_ubersaw.dds"
move 05S.dds "45- Ubersaw (BLU)/DDS/3- Field-Tested/c_ubersaw.dds"
move 05T.dds "45- Ubersaw (BLU)/DDS/4- Well-Worn/c_ubersaw.dds"
move 05U.dds "45- Ubersaw (BLU)/DDS/5- Battle Scarred/c_ubersaw.dds"

move 05V.dds "46- War Paint/DDS/1- Factory New/paintkit_tool.dds"
move 05W.dds "46- War Paint/DDS/2- Minimal Wear/paintkit_tool.dds"
move 05X.dds "46- War Paint/DDS/3- Field-Tested/paintkit_tool.dds"
move 05Y.dds "46- War Paint/DDS/4- Well-Worn/paintkit_tool.dds"
move 05Z.dds "46- War Paint/DDS/5- Battle Scarred/paintkit_tool.dds"

move 060.dds "47- Winger/DDS/1- Factory New/c_winger_pistol.dds"
move 061.dds "47- Winger/DDS/2- Minimal Wear/c_winger_pistol.dds"
move 062.dds "47- Winger/DDS/3- Field-Tested/c_winger_pistol.dds"
move 063.dds "47- Winger/DDS/4- Well-Worn/c_winger_pistol.dds"
move 064.dds "47- Winger/DDS/5- Battle Scarred/c_winger_pistol.dds"

move 065.dds "48- Wrench/DDS/1- Factory New/c_wrench.dds"
move 066.dds "48- Wrench/DDS/2- Minimal Wear/c_wrench.dds"
move 067.dds "48- Wrench/DDS/3- Field-Tested/c_wrench.dds"
move 068.dds "48- Wrench/DDS/4- Well-Worn/c_wrench.dds"
move 069.dds "48- Wrench/DDS/5- Battle Scarred/c_wrench.dds"